// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package dbgen

import (
	"context"
	"time"
)

const createItem = `-- name: CreateItem :exec

INSERT INTO items (id, owner_id, name, description, quantity, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateItemParams struct {
	ID          string
	OwnerID     string
	Name        string
	Description string
	Quantity    int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Every query is scoped by owner_id: ownership is part of the WHERE clause, so
// another user's row is indistinguishable from a missing one.
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) error {
	_, err := q.db.Exec(ctx, createItem,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Quantity,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteItem = `-- name: DeleteItem :execrows
DELETE FROM items WHERE id = $1 AND owner_id = $2
`

type DeleteItemParams struct {
	ID      string
	OwnerID string
}

func (q *Queries) DeleteItem(ctx context.Context, arg DeleteItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItem, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getItem = `-- name: GetItem :one
SELECT id, owner_id, name, description, quantity, created_at, updated_at
FROM items
WHERE id = $1 AND owner_id = $2
`

type GetItemParams struct {
	ID      string
	OwnerID string
}

func (q *Queries) GetItem(ctx context.Context, arg GetItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, arg.ID, arg.OwnerID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, owner_id, name, description, quantity, created_at, updated_at
FROM items
WHERE owner_id = $1 AND id < $2
ORDER BY id DESC
LIMIT $3
`

type ListItemsParams struct {
	OwnerID string
	ID      string
	Limit   int32
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems, arg.OwnerID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET name = $3, description = $4, quantity = $5, updated_at = $6
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, name, description, quantity, created_at, updated_at
`

type UpdateItemParams struct {
	ID          string
	OwnerID     string
	Name        string
	Description string
	Quantity    int32
	UpdatedAt   time.Time
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Quantity,
		arg.UpdatedAt,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
