// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"
)

type Item struct {
	ID          string
	OwnerID     string
	Name        string
	Description string
	Quantity    int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Session struct {
	TokenHash []byte
	UserID    string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
