// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, created_at
`

type CreateUserParams struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const createUserIfAbsent = `-- name: CreateUserIfAbsent :execrows
INSERT INTO users (id, email, password_hash, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO NOTHING
`

type CreateUserIfAbsentParams struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}

// Just-in-time provisioning of an identity-provider account (AUTH_MODE=oidc).
// ON CONFLICT (id) DO NOTHING is what makes two simultaneous first requests for
// the same subject both succeed: the loser inserts nothing and re-reads. An email
// already owned by a different row still raises the unique violation on
// users_email_key, which the adapter reports as ErrEmailTaken.
func (q *Queries) CreateUserIfAbsent(ctx context.Context, arg CreateUserIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, createUserIfAbsent,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdatePasswordHashParams struct {
	ID           string
	PasswordHash string
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users SET email = $2 WHERE id = $1
`

type UpdateUserEmailParams struct {
	ID    string
	Email string
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.ID, arg.Email)
	return err
}
