/**
 * Icons on slides — find one by meaning, draw it the same way everywhere.
 *
 * ## Why a vendored set, and why paths
 *
 * Infographics without icons read as coloured boxes; a model asked for "an
 * icon" invents names that exist nowhere. So the deck has one closed set — a
 * curated Lucide subset (`vendor/lucide/icons.ts`, ISC, regenerated by
 * `scripts/vendor-deck-icons.mjs`) — and every icon is a normalised stroke
 * path in a 24×24 box. The HTML renderer draws it as an SVG path; the
 * PowerPoint writer draws it as a native freeform (`a:custGeom`) whose line
 * colour is a theme slot, so in PowerPoint an icon is a shape the person can
 * recolour, resize and edit points of, not a picture.
 *
 * ## Why search has synonyms
 *
 * Lucide's own tags describe the drawing ("bag", "baggage"); slides talk
 * about the business ("revenue", "onboarding", "compliance"). {@link findIcons}
 * scores names and tags, then a small table of business words maps the rest,
 * so "Make this slide visual" can give each item a fitting icon and an
 * unknown icon name in the agent's input is answered with the nearest real
 * ones rather than silently dropped.
 *
 * @module shared/ui/canvas/deck-icons
 */

import { LUCIDE_ICONS } from './vendor/lucide/icons';

export const ICON_NAMES: readonly string[] = Object.keys(LUCIDE_ICONS);

export function isDeckIcon(name: unknown): name is string {
  return typeof name === 'string' && Object.prototype.hasOwnProperty.call(LUCIDE_ICONS, name);
}

/** The path data (SVG `d`) of an icon in its 24×24 box. */
export function iconPath(name: string): string | undefined {
  return isDeckIcon(name) ? LUCIDE_ICONS[name]![1] : undefined;
}

export type IconCmd = ['M' | 'L', number, number] | ['C', number, number, number, number, number, number] | ['Z'];

const parsed = new Map<string, IconCmd[]>();

/** The icon as absolute commands (what PowerPoint's freeform needs). */
export function iconCommands(name: string): IconCmd[] {
  const hit = parsed.get(name);
  if (hit) return hit;
  const d = iconPath(name) ?? '';
  const out: IconCmd[] = [];
  for (const m of d.matchAll(/([MLCZ])([^MLCZ]*)/g)) {
    const v = m[2]!.trim() ? m[2]!.trim().split(/\s+/).map(Number) : [];
    if (m[1] === 'Z') out.push(['Z']);
    else if (m[1] === 'C') out.push(['C', v[0]!, v[1]!, v[2]!, v[3]!, v[4]!, v[5]!]);
    else out.push([m[1] as 'M' | 'L', v[0]!, v[1]!]);
  }
  parsed.set(name, out);
  return out;
}

/** Business words → icons whose drawing says them. */
const SYNONYMS: Record<string, string[]> = {
  revenue: ['trending-up', 'chart-line', 'circle-dollar-sign'], growth: ['trending-up', 'sprout', 'chart-line'], profit: ['circle-dollar-sign', 'trending-up'],
  money: ['banknote', 'coins', 'wallet'], cost: ['receipt', 'calculator', 'coins'], price: ['tag', 'badge-dollar-sign'], pricing: ['tag', 'badge-dollar-sign'],
  budget: ['piggy-bank', 'calculator'], invest: ['hand-coins', 'chart-candlestick'], investment: ['hand-coins', 'chart-candlestick'], funding: ['hand-coins', 'banknote'],
  payment: ['credit-card', 'wallet'], payments: ['credit-card', 'wallet'], bank: ['landmark'], banking: ['landmark'], fintech: ['credit-card', 'smartphone'], crypto: ['bitcoin'],
  market: ['store', 'globe', 'chart-pie'], customers: ['users', 'user-check'], customer: ['user', 'user-check'], client: ['user', 'handshake'], clients: ['users', 'handshake'],
  team: ['users', 'users-round'], people: ['users'], staff: ['users', 'id-card'], employee: ['id-card', 'user'], employees: ['users', 'id-card'], hire: ['user-plus'],
  hiring: ['user-plus'], onboarding: ['user-plus', 'hand', 'rocket'], welcome: ['hand', 'party-popper'], hr: ['users', 'id-card'], culture: ['heart-handshake', 'heart'],
  benefits: ['gift', 'heart-plus'], wellbeing: ['heart-pulse', 'heart'], health: ['heart-pulse', 'stethoscope'], payroll: ['banknote', 'calendar-check'], leave: ['calendar-days', 'tent'],
  policy: ['file-text', 'scroll'], policies: ['file-text', 'scroll'], compliance: ['shield-check', 'clipboard-check'], legal: ['gavel', 'scale'], law: ['scale', 'gavel'],
  risk: ['triangle-alert', 'shield-alert'], risks: ['triangle-alert', 'shield-alert'], security: ['shield-check', 'lock'], secure: ['lock', 'shield-check'], privacy: ['eye-off', 'lock'],
  safety: ['hard-hat', 'shield-check'], performance: ['gauge', 'activity'], speed: ['zap', 'gauge'], fast: ['zap', 'rocket'], quality: ['badge-check', 'award'],
  goal: ['target', 'goal'], goals: ['target', 'goal'], objective: ['target', 'crosshair'], objectives: ['target', 'crosshair'], mission: ['flag', 'target'], vision: ['eye', 'telescope'],
  strategy: ['compass', 'route', 'puzzle'], plan: ['clipboard-list', 'map'], planning: ['clipboard-list', 'calendar'], roadmap: ['route', 'milestone', 'map'], milestone: ['milestone', 'flag'],
  launch: ['rocket'], release: ['rocket', 'package-check'], idea: ['lightbulb'], ideas: ['lightbulb'], innovation: ['lightbulb', 'sparkles'], creative: ['palette', 'brush'], design: ['pen-tool', 'palette'],
  ai: ['brain-circuit', 'bot', 'sparkles'], ml: ['brain-circuit'], automation: ['bot', 'workflow', 'cog'], data: ['database', 'chart-bar'], analytics: ['chart-bar', 'chart-pie', 'activity'],
  insight: ['lightbulb', 'eye'], insights: ['lightbulb', 'eye'], report: ['file-text', 'chart-bar'], reporting: ['chart-bar', 'file-text'], dashboard: ['layout-dashboard', 'gauge'],
  cloud: ['cloud'], server: ['server'], servers: ['server'], infrastructure: ['server', 'network'], network: ['network', 'router'], storage: ['hard-drive', 'database'],
  backup: ['database-backup', 'archive'], recovery: ['life-buoy', 'refresh-cw'], patch: ['refresh-cw', 'wrench'], update: ['refresh-cw', 'download'], upgrade: ['arrow-big-up', 'trending-up'],
  migration: ['move-right', 'cloud-upload'], integration: ['plug', 'link', 'puzzle'], api: ['code-xml', 'plug'], code: ['code'], software: ['code', 'app-window'], app: ['smartphone', 'app-window'],
  mobile: ['smartphone'], web: ['globe', 'monitor'], website: ['globe', 'monitor'], monitoring: ['activity', 'eye', 'gauge'], search: ['search'], farm: ['server', 'network'],
  sharepoint: ['layout-grid', 'files'], document: ['file-text'], documents: ['files', 'file-text'], content: ['files', 'layout-grid'], collaboration: ['users', 'messages-square', 'share-2'],
  communication: ['messages-square', 'megaphone'], email: ['mail'], support: ['life-buoy', 'headphones'], help: ['life-buoy', 'hand-helping'], service: ['hand-platter', 'headphones'],
  training: ['graduation-cap', 'presentation'], learning: ['book-open', 'graduation-cap'], learn: ['book-open', 'graduation-cap'], education: ['graduation-cap', 'school'], course: ['book-open'],
  mentor: ['users', 'graduation-cap'], buddy: ['users', 'heart-handshake'], meeting: ['users', 'calendar'], schedule: ['calendar-clock', 'calendar'], time: ['clock', 'hourglass'],
  deadline: ['alarm-clock', 'calendar-clock'], week: ['calendar-days'], day: ['sun', 'calendar'], tools: ['wrench', 'hammer'], equipment: ['laptop', 'wrench'], laptop: ['laptop'],
  access: ['key-round', 'lock-keyhole'], password: ['key-round', 'lock'], identity: ['id-card', 'fingerprint-pattern'], partner: ['handshake'], partners: ['handshake'], deal: ['handshake'],
  sales: ['chart-line', 'handshake', 'shopping-cart'], marketing: ['megaphone', 'target'], brand: ['gem', 'sparkles'], product: ['package', 'box'], products: ['boxes', 'package'],
  logistics: ['truck', 'package'], shipping: ['truck', 'ship'], delivery: ['truck', 'package-check'], supply: ['truck', 'warehouse'], operations: ['cog', 'workflow'], process: ['workflow', 'repeat'],
  energy: ['zap', 'battery-charging'], sustainability: ['leaf', 'recycle'], environment: ['leaf', 'tree-pine'], green: ['leaf', 'sprout'], global: ['globe', 'earth'], world: ['earth', 'globe'],
  location: ['map-pin'], office: ['building', 'briefcase'], company: ['building', 'briefcase-business'], business: ['briefcase-business', 'building'], award: ['award', 'trophy'], win: ['trophy'],
  success: ['trophy', 'circle-check'], done: ['circle-check', 'check-check'], complete: ['circle-check'], check: ['circle-check'], problem: ['triangle-alert', 'circle-x'], issue: ['bug', 'triangle-alert'],
  bug: ['bug'], test: ['test-tube', 'flask-conical'], testing: ['test-tube', 'list-checks'], research: ['microscope', 'flask-conical'], science: ['atom', 'flask-conical'], medical: ['stethoscope', 'pill'],
  feedback: ['message-square-quote', 'thumbs-up'], review: ['clipboard-check', 'star'], rating: ['star'], love: ['heart'], trust: ['shield-check', 'handshake'], scale: ['layers', 'trending-up'],
  scalable: ['layers', 'trending-up'], flexible: ['shuffle', 'sliders-horizontal'], simple: ['circle-check', 'sparkle'], cycle: ['repeat', 'refresh-cw'], continuous: ['infinity', 'repeat'],
  first: ['flag'], next: ['arrow-right', 'chevrons-right'], start: ['play', 'rocket'], finish: ['flag', 'trophy'], question: ['circle-question-mark'], questions: ['circle-question-mark', 'messages-square'],
};

export interface IconHit { name: string; score: number }

function words(s: string): string[] {
  return s.toLowerCase().replace(/[^a-z0-9\s-]/g, ' ').split(/[\s-]+/).filter(w => w.length > 1);
}

/** Icons for a query, best first. */
export function findIcons(query: string, limit = 12): IconHit[] {
  const q = words(query);
  if (!q.length) return [];
  const scores = new Map<string, number>();
  const add = (name: string, s: number): void => { if (isDeckIcon(name)) scores.set(name, (scores.get(name) ?? 0) + s); };
  const joined = q.join('-');
  if (isDeckIcon(joined)) add(joined, 20);
  for (const w of q) {
    const stem = w.replace(/(ies|es|s)$/, (m) => (m === 'ies' ? 'y' : ''));
    for (const [i, name] of (SYNONYMS[w] ?? SYNONYMS[stem] ?? []).entries()) add(name, 9 - i);
    for (const name of ICON_NAMES) {
      const parts = name.split('-');
      if (name === w || name === stem) add(name, 12);
      else if (parts.includes(w) || parts.includes(stem)) add(name, 5 / parts.length + 2);
      const tags = LUCIDE_ICONS[name]![0].split(/\s+/);
      if (tags.includes(w) || tags.includes(stem)) add(name, 3);
      else if (w.length >= 4 && tags.some(t => t.startsWith(w))) add(name, 1);
    }
  }
  return [...scores.entries()].map(([name, score]) => ({ name, score: Math.round(score * 10) / 10 }))
    .sort((a, b) => b.score - a.score || a.name.localeCompare(b.name)).slice(0, limit);
}

/** The best icon for some text, when one fits well enough to say the same thing. */
export function iconFor(text: string, taken: Set<string> = new Set()): string | undefined {
  const hits = findIcons(text, 8).filter(h => h.score >= 5);
  return (hits.find(h => !taken.has(h.name)) ?? hits[0])?.name;
}

/** An icon name from loose input ("Rocket", "rocket icon", "lucide:rocket"), or undefined. */
export function toIconName(v: unknown): string | undefined {
  if (typeof v !== 'string') return undefined;
  const k = v.trim().toLowerCase().replace(/^lucide[:/-]/, '').replace(/\s+icon$/, '').replace(/[\s_]+/g, '-');
  if (isDeckIcon(k)) return k;
  return findIcons(k, 1).find(h => h.score >= 8)?.name;
}
