/**
 * Build shared/kit/kit.css from the ops console's stylesheets.
 *
 *   node scripts/build-kit-css.mjs <console-src-dir>
 *
 * The widget kit came from an ops console whose styles were global and mixed
 * in with the rest of that app. This keeps only the rules whose selectors use
 * a class the kit's components actually render (read from their source), scopes
 * every one under `.aico-kit` so the kit can sit in a chat transcript without
 * restyling the page around it, keeps the keyframes those rules name, and maps
 * the console's design tokens onto AICO's theme variables.
 *
 * A script rather than a hand edit, so the result is reproducible.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const postcss = require('../desktop/node_modules/postcss');

const here = path.dirname(fileURLToPath(import.meta.url));
const kit = path.resolve(here, '../shared/kit');
const consoleSrc = process.argv[2];
if (!consoleSrc) { console.error('usage: build-kit-css.mjs <console-src-dir>'); process.exit(1); }

// Every class-looking word in the kit's components.
const classes = new Set();
for (const f of ['widgets.tsx', 'charts.tsx', 'echarts/host.tsx', 'netmap/NetworkMap.tsx', 'Cluster.tsx']) {
  const file = path.join(kit, f);
  if (!fs.existsSync(file)) continue;
  const src = fs.readFileSync(file, 'utf8');
  for (const m of src.matchAll(/className=(?:"([^"]*)"|\{`([^`]*)`\}|\{'([^']*)'\})/g)) {
    for (const word of (m[1] ?? m[2] ?? m[3] ?? '').split(/[\s$]+/)) {
      const w = word.replace(/[^a-zA-Z0-9_-].*$/, '');
      if (w.length > 1) classes.add(w);
    }
  }
  // Class names built in expressions: 'foo-' + x, `st-${...}`, cls('a', 'b').
  for (const m of src.matchAll(/'([a-z][a-z0-9-]{1,30})'/g)) classes.add(m[1]);
}

// Built in template literals the scan above cannot read; named here instead.
for (const c of ['wg', 'wg-b', 'wg-h', 'wg-f', 'wg-chart', 'wg-canvas', 'wg-chart-f', 'wg-sr', 'wg-datatable', 'dgrid']) classes.add(c);

const usesKitClass = (selector) => {
  const found = selector.match(/\.([a-zA-Z0-9_-]+)/g) ?? [];
  return found.length > 0 && found.some(c => classes.has(c.slice(1)) || [...classes].some(k => k.endsWith('-') && c.slice(1).startsWith(k)));
};

const kept = postcss.root();
const keyframesWanted = new Set();
for (const name of ['theme.css', 'chrome.css', 'chat.css']) {
  const file = path.join(consoleSrc, name);
  if (!fs.existsSync(file)) continue;
  const root = postcss.parse(fs.readFileSync(file, 'utf8'));
  root.walkRules((rule) => {
    if (rule.parent?.type === 'atrule' && /keyframes/i.test(rule.parent.name)) return;
    const selectors = rule.selectors.filter(usesKitClass);
    if (!selectors.length) return;
    const clone = rule.clone({ selectors: selectors.map(s => `.aico-kit ${s}`) });
    rule.walkDecls(/^animation(-name)?$/, (d) => { for (const w of d.value.split(/[\s,]+/)) keyframesWanted.add(w); });
    if (rule.parent?.type === 'atrule' && rule.parent.name === 'media') {
      const media = postcss.atRule({ name: 'media', params: rule.parent.params });
      media.append(clone);
      kept.append(media);
    } else {
      kept.append(clone);
    }
  });
  root.walkAtRules(/keyframes/i, (at) => { if (keyframesWanted.has(at.params)) kept.append(at.clone()); });
}

const header = `/*
 * The widget kit's styles — generated by scripts/build-kit-css.mjs from the
 * ops console these widgets came from. Do not edit by hand; rerun the script.
 *
 * Every rule is scoped under .aico-kit. The tokens below map the kit's design
 * vocabulary onto AICO's theme, so light, dark and custom themes all apply.
 */
.aico-kit {
  --bg: var(--aico-bg);
  --bg1: var(--aico-bg);
  --bg2: var(--aico-surface);
  --bg3: var(--aico-elevated);
  --line: var(--aico-border-subtle);
  --line2: var(--aico-border);
  --ln: var(--aico-border);
  --ink: var(--aico-text-primary);
  --ink1: var(--aico-text-primary);
  --ink2: var(--aico-text-secondary);
  --ink3: var(--aico-text-muted);
  --ink4: var(--aico-text-muted);
  --ok: var(--aico-success);
  --warn: var(--aico-warning);
  --crit: var(--aico-danger);
  --info: var(--aico-info);
  --accent: var(--aico-accent);
  --accent-l: var(--aico-accent-soft);
  --ev: var(--aico-accent);
  --ev-l: var(--aico-accent-soft);
  --ev-w: color-mix(in srgb, var(--aico-accent) 30%, transparent);
  --warn-w: color-mix(in srgb, var(--aico-warning) 22%, transparent);
  --crit-w: color-mix(in srgb, var(--aico-danger) 22%, transparent);
  --heat: var(--aico-danger);
  --mono: var(--aico-font-mono);
  --sans: var(--aico-font);
  --r1: 4px;
  --r2: 10px;
  --r3: 14px;
  --sh1: 0 1px 2px rgba(0,0,0,.08);
  font-family: var(--sans);
  color: var(--ink);
}

`;
fs.writeFileSync(path.join(kit, 'kit.css'), header + kept.toString() + '\n');
console.log(`kit.css: ${kept.nodes.length} rules from ${classes.size} class names`);
