/**
 * "What this agent can do", generated by the engine (design §7.6).
 *
 * WHY GENERATED. A summary someone writes by hand is a claim; this one is
 * computed with the functions the run itself uses — `agentRunScope` for the
 * scope, `resolveToolSet` for the built-ins offered, `mcpToolAllowed` for MCP
 * tools, the custom-tool store and `approvalDecision` for custom tools, and
 * `agents/ceiling`'s level rules for what asks. So it is true by construction,
 * and the Phase 3 harness test holds the three (summary, offered, dispatched)
 * equal on one fixture.
 *
 * The level it describes is the agent's ceiling (L3 when unset). A session in
 * a stricter mode only makes the agent ask more, and the summary says so
 * rather than pretending to know the session.
 *
 * What it does not do: decide anything. It reads; every decision stays in the
 * run's own guards.
 *
 * @module agents/summary
 */

import { boundsOf } from './resolve.js';
import { EDIT_TOOLS } from './ceiling.js';
import { scopeAllows } from './effective.js';
import { levelLabel, parseLevel, levelRank, type AutonomyLevel } from '../autonomy/levels.js';
import type { AgentBounds, AgentSpec } from './types.js';

export interface AgentSummary {
  name: string;
  level: AutonomyLevel;
  /** Every tool the agent may call, sorted: built-ins, then custom, then MCP. */
  tools: string[];
  runsWithoutAsking: string[];
  asksFirst: string[];
  /** Things it cannot do, in words. */
  cannot: string[];
  delegation: string;
  budget: string;
  writes: string;
  unattended: string;
  notes: string[];
  /** The whole thing as one paragraph, for a tool result or a terminal. */
  text: string;
}

/** Tools whose name says nothing to a person; listed by what they do instead. */
const DELEGATION = new Set(['Task', 'Investigate']);

function list(names: string[], max = 12): string {
  if (names.length <= max) return names.join(', ');
  return `${names.slice(0, max).join(', ')} and ${names.length - max} more`;
}

/** Summarise a definition (saved or not) as the engine will run it. */
export async function summarizeAgent(spec: AgentSpec | (Partial<AgentSpec> & { name: string }), cwd: string): Promise<AgentSummary> {
  const full: AgentSpec = {
    description: '', role: '', goals: [], skills: [], tools: [], canDelegate: true, reportFormat: '',
    systemPromptXml: '', source: 'user', ...spec,
  } as AgentSpec;
  const bounds: AgentBounds = boundsOf(full);
  const { agentRunScope, resolveToolSet, mcpToolAllowed, isReadOnlyBuiltin } = await import('../agent.js');
  const { loadSettings } = await import('../settings.js');
  const { mcpRegistry } = await import('../mcp/registry.js');
  const { loadCustomTools, usableTools } = await import('../custom-tools/store.js');
  const { approvalDecision } = await import('../custom-tools/policy.js');

  const settings = await loadSettings().catch(() => undefined);
  const level: AutonomyLevel = parseLevel(bounds.autonomy) ?? 'L3';
  const rank = levelRank(level);
  const planMode = rank === 0;
  const scope = agentRunScope({ ...(bounds.tools ? { agentSpecTools: bounds.tools } : {}), agentBounds: bounds, cwd });

  // Built-ins, exactly as a run resolves them (persona at depth 0).
  const { defs } = resolveToolSet({
    ...(bounds.tools ? { agentSpecTools: bounds.tools } : {}),
    ...(settings ? { settings } : {}),
    planMode,
    depth: 0,
    scope,
  });
  const builtins = defs.map(d => d.name).filter(n => !DELEGATION.has(n));
  const delegation = [...DELEGATION].filter(n => scope.delegate && scopeAllows(scope, n));

  const custom = [...usableTools(await loadCustomTools(cwd).catch(() => [])).values()]
    .filter(t => scopeAllows(scope, t.name) && (!planMode || t.def.effect === 'read'));
  const mcp = mcpRegistry.getToolsForAgent()
    .map(t => t.name)
    .filter(n => mcpToolAllowed(n, { scope, planMode, settings }));

  const runsWithoutAsking: string[] = [];
  const asksFirst: string[] = [];
  for (const name of builtins) {
    const autoAt = isReadOnlyBuiltin(name) ? 0 : EDIT_TOOLS.has(name) ? 2 : 3;
    (rank >= autoAt ? runsWithoutAsking : asksFirst).push(name);
  }
  for (const t of custom) {
    const decision = approvalDecision(t.name, t.def.effect, t.def.approval, { planMode, autoApprove: rank >= 3 });
    (decision.kind === 'allow' ? runsWithoutAsking : asksFirst)
      .push(decision.kind === 'ask' && decision.mode !== 'standard' ? `${t.name} (${decision.mode})` : t.name);
  }
  for (const name of mcp) (rank >= 3 ? runsWithoutAsking : asksFirst).push(name);

  const cannot: string[] = [];
  const hasWrite = builtins.some(n => EDIT_TOOLS.has(n));
  const hasShell = builtins.includes('Bash') || builtins.includes('Terminal');
  if (!hasWrite) cannot.push('change files with the file tools');
  if (!hasShell) cannot.push('run shell commands');
  if (!mcp.length) cannot.push('use MCP tools');
  if (planMode) cannot.push('do anything but read (L0, plan)');

  const delegate = bounds.delegate;
  const delegationText = !delegation.length || delegate === 'none' ? 'cannot delegate'
    : delegate === 'readonly' ? 'may delegate read-only research only'
      : Array.isArray(delegate) ? `may delegate only to ${delegate.join(', ')}` : 'may delegate';
  if (!delegation.length || delegate === 'none') cannot.push('delegate');

  const b = bounds.budget;
  const budgetText = b && (b.maxUsd || b.maxIterations || b.maxMinutes)
    ? `spends at most ${[b.maxUsd ? `$${b.maxUsd}` : '', b.maxIterations ? `${b.maxIterations} steps` : '', b.maxMinutes ? `${b.maxMinutes} min` : ''].filter(Boolean).join(' / ')} per run`
    : 'has no budget of its own (the session\'s limits apply)';

  const writes = bounds.writePaths?.length
    ? `AICO's file tools may write only ${bounds.writePaths.join(', ')}${hasShell ? ' — Bash is not bound by this and can write anywhere' : ''}`
    : hasWrite ? 'may write anywhere in the project with the file tools' : 'writes nothing with the file tools';

  // L4 needs a current certificate (evals/certificate); the run's own model
  // decides it, so this reads the status on the configured one.
  let unattended = `not allowed (its ceiling is ${levelLabel(level)})`;
  if (level === 'L4') {
    const { isCertified } = await import('../evals/certificate.js');
    const cert = await isCertified(full.name, { cwd, model: full.model || settings?.model || '' }).catch(() => undefined);
    unattended = cert?.ok
      ? `allowed — ${cert.reason}; anything that needs a person is parked in the inbox`
      : `only with a current certificate, and it is ${cert?.reason ?? 'not certified'} — until then unattended runs are held to L3 (aico agent certify ${full.name})`;
  }

  const notes = [
    'A session in a stricter mode (plan, ask, edits) makes it ask more, never less.',
    ...(rank === 3 ? ['At L3, Bash commands still pass the safety classifier, and destructive custom tools ask every time.'] : []),
  ];

  const tools = [...builtins, ...delegation, ...custom.map(t => t.name), ...mcp];
  const text = [
    `${full.name} (${levelLabel(level)})`,
    runsWithoutAsking.length ? `Can, without asking: ${list(runsWithoutAsking)}.` : 'Can do nothing without asking.',
    asksFirst.length ? `Asks you before: ${list(asksFirst)}.` : '',
    cannot.length ? `Cannot: ${cannot.join('; ')}.` : '',
    `Delegation: ${delegationText}.`,
    `Budget: ${budgetText}.`,
    `Writes: ${writes}.`,
    `Unattended: ${unattended}.`,
  ].filter(Boolean).join('\n');

  return {
    name: full.name, level, tools, runsWithoutAsking, asksFirst, cannot,
    delegation: delegationText, budget: budgetText, writes, unattended, notes, text,
  };
}
