/**
 * `Evidence`: the change packet, for the model to attach to a pull request or
 * a commit (ADR 0034).
 *
 * Deferred (group `evidence`, tools/deferred.ts): the schema costs nothing until
 * a request about a PR, a commit message or "what did you verify" loads it.
 *
 * The model's own summary of its work is the claim a reviewer cannot check; this
 * tool hands it the record instead, built from the run's session log and git,
 * so the description it writes is the record rather than its recollection. Read
 * only. `short` is the one- or two-line `Verified: …` form for a commit body;
 * neither form carries authorship or credit, and the description says so
 * because a model asked to "write a commit message" reaches for a footer.
 *
 * @module tools/evidence
 */

import { currentRunContext, projectRoot } from '../run-context.js';
import { packetFromEvents, render, type EvidenceFormat } from '../evidence/index.js';

export interface EvidenceInput {
  format?: EvidenceFormat;
  /** Diff against this ref instead of the merge base with the default branch. */
  base?: string;
}

export async function evidenceTool(input: EvidenceInput = {}): Promise<string> {
  const ctx = currentRunContext();
  const log = ctx?.sessionLog;
  if (!log) return 'Evidence needs this run\'s session log, and this run has none (a one-shot run without a log). Nothing is recorded to report on.';
  const format: EvidenceFormat = input.format === 'json' || input.format === 'short' ? input.format : 'md';
  const base = typeof input.base === 'string' && /^[\w./~^@{}-]{1,100}$/.test(input.base) && !input.base.startsWith('-') ? input.base : undefined;
  const packet = await packetFromEvents(log.events(), {
    root: projectRoot(),
    ...(ctx?.sessionId ? { sessionId: ctx.sessionId } : {}),
    ...(base ? { base } : {}),
    ...(ctx?.settings ? { settings: ctx.settings } : {}),
  });
  const text = render(packet, format);
  return format === 'short'
    ? `${text}\n\n(Put this line in the commit body as it is. Do not add authorship, "generated by" or co-author lines — the project forbids them.)`
    : text;
}

export const evidenceDefinition = {
  name: 'Evidence',
  description:
    'Build the change evidence report for this session from its log and git: files changed (+/-), every check run '
    + 'with command, exit code and counts, VerifyApp results, scans, approvals and denials, models and cost, open gaps. '
    + 'Paste format "md" into a PR description; use "short" for a commit-body "Verified:" line. Facts only: '
    + 'anything not run is shown as not run. Never add authorship or credit lines to the commit or PR.',
  inputSchema: {
    type: 'object' as const,
    properties: {
      format: { type: 'string', enum: ['md', 'short', 'json'], description: 'md (default) for a PR description, short for a commit body, json for tools.' },
      base: { type: 'string', description: 'Diff against this ref (default: merge base with the default branch).' },
    },
  },
};
